[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10"
lazy_static = "1"
nom = "7"
regex = "1"
